# Generated by Django 5.2.3 on 2025-07-10 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("weather_site", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="city",
            name="country",
        ),
        migrations.RemoveField(
            model_name="city",
            name="latitude",
        ),
        migrations.RemoveField(
            model_name="city",
            name="longitude",
        ),
        migrations.RemoveField(
            model_name="city",
            name="name",
        ),
        migrations.RemoveField(
            model_name="weatherdata",
            name="description",
        ),
        migrations.RemoveField(
            model_name="weatherdata",
            name="feels_like",
        ),
        migrations.RemoveField(
            model_name="weatherdata",
            name="icon",
        ),
        migrations.RemoveField(
            model_name="weatherdata",
            name="temperature",
        ),
        migrations.RemoveField(
            model_name="weatherdata",
            name="timestamp",
        ),
        migrations.AddField(
            model_name="city",
            name="place_id",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="weatherdata",
            name="data",
            field=models.JSONField(null=True),
        ),
    ]
