# Generated by Django 5.2.3 on 2025-07-10 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "weather_site",
            "0002_remove_city_country_remove_city_latitude_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="city",
            name="data",
            field=models.JSONField(null=True),
        ),
        migrations.DeleteModel(
            name="WeatherData",
        ),
    ]
