# Generated by Django 5.2.3 on 2025-07-10 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("weather_site", "0003_city_data_delete_weatherdata"),
    ]

    operations = [
        migrations.AlterField(
            model_name="city",
            name="data",
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name="city",
            name="place_id",
            field=models.IntegerField(unique=True),
        ),
    ]
